# Generated by Django 5.0.7 on 2024-07-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kangacook', '0002_recipe_delete_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='steps',
            new_name='description',
        ),
    ]
